# if getting service account permissions issues with litmus resources, try this rolebinding
# TODO: restrict these permissions to least privilege
apiVersion: v1
kind: ServiceAccount
metadata:
  name: argo-chaos
  namespace: litmus
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: chaos-cluster-role
rules:
- apiGroups:
  - '*'
  resources:
  - '*'
  verbs:
  - '*'
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: chaos-cluster-role-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: chaos-cluster-role
subjects:
- kind: ServiceAccount
  name: argo-chaos
  namespace: litmus
- kind: ServiceAccount
  name: litmus
  namespace: litmus
- kind: ServiceAccount
  name: default
  namespace: litmus
- kind: ServiceAccount
  name: litmus-cluster-scope
  namespace: litmus
